# Generated by Django 3.1.2 on 2020-11-08 06:07

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_moods',
            field=models.JSONField(default=apps.accounts.models.default_moods),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default='About Me'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='goal_moods',
            field=models.JSONField(default=apps.accounts.models.default_moods),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
